#--- Partial FS Earth Tiles ini datas ---

[FSEarthTiles]

AreaDefinitionMode       = 2Points
NorthWestCornerLatitude  = 42deg 49min 10.49sec north
NorthWestCornerLongitude = 141deg 39min 8sec east
SouthEastLatitude        = 42deg 45min 18.29sec north
SouthEastLongitude       = 141deg 42min 25.75sec east
